version: 2.1

jobs:
  build:
    environment:
      CC_TEST_REPORTER_ID: 540fea75bbb667c00540fcf34720c5204d51d7da947bddbbd1df9ae7b75313ef
    docker:
      - image: circleci/node:12.13.0
      - image: circleci/redis
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: ${POSTGRES_USER}
          POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
          POSTGRES_DB: testdb
